# Generated by Django 6.0.1 on 2026-02-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('Asset_ID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('LP', 'Laptop'), ('MONITOR', 'Monitor'), ('SU', 'System Unit'), ('MOUSE', 'Mouse'), ('KB', 'Keyboard')], max_length=10)),
                ('status', models.CharField(choices=[('AVAIL', 'Available'), ('BUSY', 'Assigned'), ('REPAIR', 'Under Repair')], default='AVAIL', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=11)),
                ('department', models.CharField(max_length=255)),
                ('work_mode', models.CharField(choices=[('SITE', 'On-Site'), ('WFH', 'Work From Home')], default='SITE', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_assets', to='app.employee'),
        ),
    ]
